[package]
name = "rust_http_server"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.0"
axum = "0.8.9"
chrono = "0.4.45"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tower-cookies = "0.11.0"
tower-http = { version = "0.7", features = ["fs"] }
uuid = { version = "1", features = ["v4"] }
walkdir = "2.5.0"
