CREATE TABLE sessions (
    id VARCHAR(255) PRIMARY KEY,
    uuid VARCHAR(255) UNIQUE NOT NULL,
    dateCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    dateExpires TIMESTAMPTZ NOT NULL DEFAULT NOW()
);